name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify your Python version
        # Optionally specify node-version if needed
        # node-version: '16'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install distutils
        pip install -r requirements.txt

    - name: Run tests
      run: |
        # Add commands to run your tests here
        echo "Running tests..."

    - name: Build Docker image
      run: |
        docker build -t myapp .

    - name: Run Docker container
      run: |
        docker run -d -p 8501:8501 myapp
